#!/usr/bin/env python
import sys
import os
from re import split
import datetime

"""
This script requires 3 arguments: 
	input_directory
	output_directory
	your name.

It uses a natural sort to get the filenames in order. 
The mystery awaits you. GO FORTH!
"""


#Test for int or string
def tryint(s):
    try:
        return int(s)
    except ValueError:
        return s
     

#Natural sort using regex to split numbers from string
def alphanum_key(s):
    return [ tryint(c) for c in split('([0-9]+)', s) ]


#Go through characters of each file looking for uppercase letters
def extract_capitals(directory):

	message = ''

	filelist = os.listdir(directory)
	filelist.sort(key=alphanum_key)	#Sort the filenames alphanumerically
	for filename in filelist:
		filepath = os.path.join(directory, filename)
		file=open(filepath,"rt")

		if file.mode == 'rt':

			#char = file.read(1)	#Alternate version to pull the characters
			#while char:
			#	if char.isupper():
			#		message += char
			#	char = file.read(1)

			for line in file:
				for char in line:
					if char.isupper():
						message += char

	return message


#Write contents to a file named with your name and date.
def write_file(contents, directory, name):
	try:
		filepath = os.path.join(directory, name + "_" + datetime.datetime.now().strftime("%Y-%m-%d %H%M%S") + ".txt")
		file = open(filepath, "w")
		file.write(contents)
		file.close()
		
		print("Secret message '" + contents  + "' has been written to '" + filepath + "'!")
	
	except:
		print("Error writing output file.")


def main(argv):
	if len(argv) == 3:
		input_directory = argv[0]
		output_directory = argv[1]
		name = argv[2]

		secret_message = extract_capitals(input_directory)

		write_file(secret_message, output_directory, name)

	else:
		print("Please enter 3 arguments: input directory, output directory, your name.")


if __name__ == '__main__':
	main(sys.argv[1:])
